### ISSUE TITLE
Add `search` feature

### ISSUE THREAD

**Issue by Nosudrum** [TheSpaceDevs/spaceflightnewsapi#185]
Should apply to `title`, `summary`, and `news_site` fields

**Comment by derkweijers** [comment]
Should be implemented now in rc.7

**Comment by derkweijers** [comment]
I can expand it, but it looked more useful for just title and summary? That's what `search` is doing on v3.

**Comment by Nosudrum** [comment]
`search` is a quite wide parameter, where you want all the possible content relevant to a keyword. With that in mind I think it should also apply to the `news_site`, e.g. if you want all CNBC or NASA-related content, you also probably want all the articles by CNBC or NASA (even if they don't include the keyword in title or summary, which happens regularly for the former).

If people want to only have results with the keyword in title or summary, they can do two calls with the appropriate title and summary filters.
