### ISSUE TITLE
Add sorting

### ISSUE THREAD

**Issue by Nosudrum** [TheSpaceDevs/spaceflightnewsapi#188]
For the following fields:

- [x] `title`
- [ ] `news_site`
- [x] `summary`
- [x] `published_at`
- [x] `updated_at`

**Comment by Nosudrum** [comment]
Not sure if for news sites it should be `news_site` or `news_site__name` in `ordering_fields`. Gotta test.

**Comment by derkweijers** [comment]
Should be implemented now in rc.7. Not news_site though, but on dates for now.

**Comment by Nosudrum** [comment]
Yeah not sure ordering on news_sites has any use case though
